import pygame
import numpy as np

#colors
WHITE = [255, 255, 255]
YELLOW = [255, 255, 0]
BLACK = [0, 0, 0]
GRAY = [128, 128, 128]
BLUE = [0, 128, 255]

#background settings
BOARDER = 10
CARD_SPACING = 5
FIG_WIDTH = 372 // 3
FIG_HEIGHT = 587 // 3
FIG_SIZE = [FIG_WIDTH, FIG_HEIGHT]
CARD_BOARDER = 5
CARD_WIDTH = 2 * CARD_BOARDER + FIG_WIDTH
CARD_HEIGHT = 2 * CARD_BOARDER + FIG_HEIGHT
CARD_SIZE = [CARD_WIDTH, CARD_HEIGHT]
DECK_WIDTH = 600
MIDDLE_SPACING = 20
WINDOW_WIDTH = BOARDER * 2 + (CARD_SPACING + CARD_WIDTH) * 8 - CARD_SPACING + DECK_WIDTH
WINDOW_HEIGHT = 4 * CARD_HEIGHT + 4 * MIDDLE_SPACING
WINDOW_SIZE = (WINDOW_WIDTH, WINDOW_HEIGHT)
WINDOW_CENTER = [WINDOW_WIDTH / 2, WINDOW_HEIGHT / 2]
WINDOW_RECT = pygame.Rect(0, 0, WINDOW_WIDTH, WINDOW_HEIGHT)
UP_CARD_POS = [[BOARDER + i * (CARD_SPACING + CARD_WIDTH), BOARDER] for i in range(0, 8)]
DOWN_CARD_POS = [[p[0], WINDOW_HEIGHT - BOARDER - CARD_HEIGHT] for p in UP_CARD_POS]
POOL_WIDTH = 8
MIDDLE_BUFFER = MIDDLE_SPACING + CARD_HEIGHT
MIDDLE_CARD_X = [BOARDER + (i + 1) * (MIDDLE_SPACING + CARD_WIDTH) for i in range(0, POOL_WIDTH)]
MIDDLE_CARD_POS = [[x, BOARDER + i * MIDDLE_BUFFER] for x in MIDDLE_CARD_X for i in range(1, 3)]
CARD_POS = UP_CARD_POS + DOWN_CARD_POS + MIDDLE_CARD_POS[:8]
DECK_SIZE = 8
POOL_SIZE = 8
COVER_BOARDER = 10

